name: "Policy Remove"
description: "Remove policy image"
author: "Aserto Inc."
branding:
  icon: delete
  color: blue
inputs:
  tag:
    description: "tag of policy image to be removed"
    required: true
  verbosity:
    description: "verbosity level [info|error|debug|trace]"
    required: true
    default: error
runs:
  using: docker
  image: 'docker://ghcr.io/opcr-io/policy:0.1'
  entrypoint: /app/rm.sh
